#####################################################################################
#   Base Configuration - contains all the objects that are used in the experiment   #
#####################################################################################

# Model Architecture
model:
  type: "Network"
  layers:


# Optimizer
optimizer:
  type: MomentumOptimizer
  lr: 1
  momentum: 0.99

# LR Scheduler
lr_scheduler:
  type: StepLR
  args:
    step_size: 5
    gamma: 0.9

# Loss Function
loss:
  type: "BinaryLoss"

# Dataset
dataset:
  type: "RandomDataset"
  input_size: 500
  len: 1000
  root: "./outputs/data/random"  # Path to the dataset
  normalize: False  # Normalize values to [0, 1]
  flatten: True

  encoder:
    type: "LatencyEncoder"
    size: 500
    max_value: 1.0

# Pipeline
pipeline:
  type: "TrainingPipeline"
  epochs: 5
  batch_size: 64
  validation_split: 0.2
  test_split: 0.2
  early_stopping_patience: 15
  shuffle: True

  # Callbacks (Optional)
  callbacks:
    - type: "MetricsTracker"
    - type: "EarlyStopping"
      metric: "val_loss"
      patience: 3
      min_delta: 5.0
      verbose: True
    - type: "MlflowCallback"
      experiment_name: ""
      root_dir: "./outputs"
    - type: "ModelCheckpoint"
      filename: "model_{epoch}.pkl"
      save_best_only: True