name: mnist_experiment
id: 1
desc: Training MNIST with different perceptron architectures
config_dir_path: examples/mnist_experiment/configs  # Path to config files
trial_names:
  - small_perceptron
  - medium_perceptron
  - large_perceptron
settings:
  device: cuda  # Will be overridden by CPU if CUDA not available
